[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.9.0"

# otherwise links would not work properly
[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"